name: Go Build and Deploy

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.22.3'  # 根据你项目的 Go 版本调整

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: ~/.cache/go-build
        key: ${{ runner.os }}-go-mod-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-mod-

    - name: Install dependencies
      run: |
        go mod tidy

    - name: Build Go project
      run: |
        go build -o icu ./cmd/icu

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: icu
        path: ./icu 
